### ISSUE TITLE
Unfair comparison with quickmenu

### ISSUE THREAD

**Issue by emarsk** [Timoses/vim-venu#14]
Hi, in the main README.md, you state that [quickmenu](https://github.com/skywind3000/quickmenu.vim) doesn't support submenus, but this is false.
In fact, submenus in quickmenu are pretty straightforward (although not very well documented, to say the least):

```
" main menu
call quickmenu#current(0)
call quickmenu#reset()
call quickmenu#append("Submenu …", 'call quickmenu#toggle(1)')

" submenu
call quickmenu#current(1)
call quickmenu#reset()
call quickmenu#append("Does it work?", ':echo "It works!"')
```

**Comment by Timoses** [comment]
Thanks for the hint.

I removed the incorrect description item: https://github.com/Timoses/vim-venu/commit/21accb644e80b8a556d01c8c9972f2159883bc02
